disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Skeptical Labs LLC"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Operations consulting for startups and government. We build systems, create data visibility, and drive decisions."
  copyright = "Skeptical Labs LLC"

[params.author]
  name = "Skeptical Labs LLC"
  email = "will@skepticallabs.com"
  headline = "Operations Consulting"
  bio = "We walk into dysfunction, build systems to create data visibility, and use that data to drive decisions."
  links = [
    { email = "mailto:will@skepticallabs.com" },
    { linkedin = "https://linkedin.com/in/willhea" },
    { link = "https://willhea.com" },
  ]
